Repository oreboot/oreboot, pull requests merged in 2022-11, with the labels that each got.

#620 Lint github auto-merge manifest
  .github/auto-merge.yml
Labels: automerge

#631 CI: Upgrade checkout actions to 'v3'
  .github/workflows/build.yml
Labels: automerge

#637 emulation/qemu-riscv64 Add temporary qemu info
  src/mainboard/emulation/qemu-riscv/QEMU.md
Labels: automerge, Awaiting Reviewer

#638 tools/layoutflash: bring it back
  tools/layoutflash/Cargo.toml
  tools/layoutflash/data/16bytes
  tools/layoutflash/data/RomImage
  tools/layoutflash/data/fixed-dtfs.dtc
  tools/layoutflash/data/fixed-dtfs.dts
  tools/layoutflash/src/main.rs
Labels: Awaiting Reviewer
